# Command to all profiles
app:
  version: "0.1"
spring:
  main:
    banner-mode: "off"
  web:
    resources:
      add-mappings: "false"
  mvc:
    throw-exception-if-no-handler-found: "true"
   # Uncomment the following to disable the security during development
  # autoconfigure:
  #   exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

logging:
  # config: ./config/logback.xml
  pattern:
    file: "%d{dd-MM HH:mm} - %-5level - %logger{1} - %msg%n"
  file:
    name: logs/app.log
  level:
    root: INFO
    org:
      hibernate: error
      springframework: WARN
    com:
      mak: INFO
